-- =============================================================================
-- Webnua backend — funnel offer (AI-generated, user-editable).
--
-- Stores the four-field offer the wizard generates from the funnel brief
-- (service / customer-pain / guarantee). The offer is the spine of the
-- funnel — its headline, promise, risk-reversal and CTA flow into the
-- funnel landing-page hero, CTA section, and trust pills. Generated by
-- /api/generate-offer (Sonnet 4.6) and editable in the wizard before
-- final submit, so what lands here is what the operator approved.
--
-- Single jsonb column rather than four text columns because the four
-- fields are one unit of data — always created together, always edited
-- together, always rendered together. Matches the existing
-- funnel_testimonials shape.
--
-- Shape: { headline, promise, risk_reversal, cta_text } — snake_case keys
-- to match the rest of the DB; mapped to camelCase at the boundary.
-- =============================================================================

alter table public.funnels
  add column funnel_offer jsonb;

comment on column public.funnels.funnel_offer is
  'Four-field structured offer { headline, promise, risk_reversal, cta_text } generated by /api/generate-offer and editable in the wizard. NULL until the wizard runs offer generation.';
