-- =============================================================================
-- 0046 — Add website_approval_submissions to the supabase_realtime publication.
--
-- B1. The approval write path is Supabase (website_approval_submissions); the
-- editor's publish-state surfaces and the operator approvals queue on /tickets
-- read it live. Until now neither side subscribed via Realtime — the queue
-- relied on the in-app BUILDER_EVENT bus + query invalidation, which only
-- propagates within the tab that fired the mutation. A second operator
-- approving from another session would not see the queue update without a
-- manual refresh.
--
-- Adding the table to the publication lets RealtimeProvider subscribe via
-- postgres_changes. RLS is still applied to broadcast rows for the
-- authenticated role — an operator receives changes only for submissions they
-- may SELECT (the same posture as notifications / tickets in migration 0032).
-- =============================================================================
alter publication supabase_realtime add table public.website_approval_submissions;
